### ISSUE TITLE
Double Hotbar Compatibility

### ISSUE THREAD

**Issue by ardissaps** [LordAnaku/Anakus_Status_Bars#1]
Would you please make it compatible with : 
https://www.curseforge.com/minecraft/mc-mods/double-hotbar
![image](https://user-images.githubusercontent.com/82106625/186330588-c201b010-01b8-4e12-bab1-b972057d2c6d.png)

Thanks!

**Comment by LordAnaku** [comment]
Added ability to change position of bars.
