### ISSUE TITLE
Display Number in addition to Bar

### ISSUE THREAD

**Issue by ardissaps** [LordAnaku/Anakus_Status_Bars#3]
Would you please add number inside the bar like "current/max" inside the bar? It would be very useful for mod that can make healt or armor or other with quite high number

**Comment by LordAnaku** [comment]
Currently working on rewriting mod for forge (first time modding Minecraft [and java for that matter] and wanted to make same mod with both to see what version I liked working with better). Anyways... its on the todo list for when I come back here after finishing that to clean up the code and fix some oversights I now know about.

**Comment by ardissaps** [comment]
@LordAnaku thank you for the number addition, it would be great if there is an option to make the number inside the bar (armor value outside the bar, armor durability inside the bar). But the icon still better on the outside I think, only the number that could be inside (configurable).
![image](https://user-images.githubusercontent.com/82106625/188419305-42dc8d3b-95b0-4547-bbe3-27b95cf19652.png)
Not in a hurry, take your time! :)

**Comment by LordAnaku** [comment]
That was my original plan, but the way Minecraft scales textures made that a living nightmare to do. (unless I was missing something)
